# Generated by Django 5.1.3 on 2024-11-20 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='国内团购旅游方案名')),
                ('description', models.CharField(max_length=350, verbose_name='国内团购旅游方案介绍')),
                ('price', models.CharField(max_length=100, verbose_name='团购价格')),
                ('image', models.ImageField(upload_to='tour/images/', verbose_name='团购旅游图片')),
                ('url', models.URLField(blank=True, verbose_name='国内团购旅游资源链接')),
            ],
            options={
                'verbose_name': '国内团购旅游',
                'verbose_name_plural': '国内团购旅游',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('watchAgain', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
